/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package core;

public class Hello {
	private final String name;
	public Hello(String name) {
		this.name = name;
	}
    public String get() {
        return "Hello " + name;
    }
}
