import java.util.*;

// see https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3590
class JavacBoom200 {
	List<Map.Entry<String, String>> data = Arrays.asList(
		Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"),
		Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"),
		Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"),
		Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"),
		Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"),
		Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"),
		Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"),
		Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"),
		Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"),
		Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"),
		
		Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"),
		Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"),
		Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"),
		Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"),
		Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"),
		Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"),
		Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"),
		Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"),
		Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"),
		Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value"), Map.entry("key", "value")
	);
}