/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import core.Hello;

public class App {
    public static void main(String[] args) {
    	System.out.println(new Hello("world").get());
	}
}
